services:
  app:
    build: /SacStateApp
    ports:
      - "8081:8081"
  admin-web:
    build: ./admin-web
    ports:
      - "3000:3000"
  backend:
    build: ./backend-api
    ports:
      - "5000:5000"
