// styles/SignUpStyles.js
import { StyleSheet } from 'react-native';
import * as colors from '../SacStateColors/GeneralColors';

const styles = StyleSheet.create({
    background: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.darkOverlay,
        width: '100%',
        padding: 16,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 10,
        color: colors.mutedGold,
        textAlign: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        textShadowColor: colors.black,
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 4,
    },
    box: {
        backgroundColor: colors.mutedDarkGreen,
        borderRadius: 20,
        padding: 25,
        width: '90%',
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 6,
        alignItems: 'center',
        borderColor: colors.subtleFadedGold,
        borderWidth: 1.5,
    },
    input: {
        height: 45,
        borderColor: colors.fadedGold,
        borderWidth: 1.5,
        marginBottom: 15,
        paddingHorizontal: 15,
        backgroundColor: colors.opaqueWhite,
        borderRadius: 8,
        width: '100%',
        fontSize: 16,
        color: colors.sacGreen,
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        backgroundColor: colors.opaqueWhite,
        borderRadius: 8,
        borderColor: colors.fadedGold,
        borderWidth: 1.5,
        paddingHorizontal: 15,
        marginBottom: 15,
    },
    passwordInput: {
        flex: 1,
        height: 45,
        fontSize: 16,
        color: colors.sacGreen,
    },
    eyeIcon: {
        padding: 10,
    },
    button: {
        backgroundColor: colors.mutedSacStateGreen,
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 8,
        alignItems: 'center',
        width: '60%',
        marginTop: 10,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 6,
        borderColor: colors.subtleFadedGold,
        borderWidth: 1.5,
    },
    buttonText: {
        color: colors.softCream,
        fontSize: 18,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    linkText: {
        marginTop: 15,
        color: colors.white,
        textDecorationLine: 'underline',
        fontSize: 16,
    },
});

export default styles;
